import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { useLoadState } from "./loadState";

import { cn } from "@/lib/utils"

import Nav from "./nav";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <div className="container p-12 mx-auto">
          <div className="flex flex-row flex-wrap">
            <nav className="w-full sm:w-1/3 md:w-1/4 bg-slate-50 mr-8 p-4 rounded-lg">
              <Nav />
            </nav>
            <main role="main" className="prose w-full sm:w-2/3 md:w-3/4">
              {children}

            </main>
          </div>
        </div>
      </body>
    </html >
  );
}
