import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} prose`}>
        <div className="container mx-auto">
          <div className="flex flex-row flex-wrap py-4">

            <div className="px-2">
              <h1>Web Vitals Demos</h1>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
